language: python
python:
  - '3.7'

branches:
  only:
    - travis

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

script:
  - ./manage.py collectstatic
  - ./manage.py test
