language: python

python:

  - '3.7'

# safelist

branches:

  only:

    - travis


before_script:

  - pip install -r requirements.txt


env: DJANGO_SETTINGS_MODULE="pur_beurre.travis_settings"

services:

  - mysql

script:

  - python manage.py test
