language: python
python:
  - '3.7'

# safelist
branches:
  only:
    - travis

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

script:
  - ./manage.py test
