language: python
python:
  - '3.7'

branches:
  only:
    - travis

before_script:
  - pip install -r requirements.txt

services:
  - pysql

env: DJANGO_SETTINGS_MODULE=pur_beurre.travis

script:
  - ./manage.py test
